routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TaskController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/tasks');
});

Route::get('tasks/active', [TaskController::class, 'active'])->name('active');
Route::get('tasks/completed', [TaskController::class, 'completed'])->name('completed');
Route::get('/changestatus', [TaskController::class, 'changeStatus'])->name('changestatus');
Route::get('/deleteall', [TaskController::class, 'deleteAll'])->name('deleteall');
Route::get('/completedall', [TaskController::class, 'completedAll'])->name('completedall');
Route::resource('tasks', TaskController::class)->only('index', 'store', 'destroy');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $table = 'tasks';
    protected $fillable = [
        'title',
        'is_complete',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/TaskController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Validator;
use App\Models\Task;
use App\Http\Resources\TaskResource;

class TaskController extends Controller
{
    public function index()
    {
        $data = Task::latest()->get();
        return response()->json([TaskResource::collection($data), 'Task fetched.']);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'title' => 'required|string|max:255'
        ]);

        if($validator->fails()){
            return response()->json($validator->errors());       
        }

        $task = Task::create([
            'title' => $request->title,
            'is_complete' => false
         ]);
        
        return response()->json(['Task created successfully.', new TaskResource($task)]);
    }

    public function show($id)
    {
        $task = Task::find($id);
        if (is_null($task)) {
            return response()->json('Data not found', 404); 
        }
        return response()->json([new TaskResource($task)]);
    }

    public function update(Request $request, Task $task)
    {
        $task->is_complete = true;
        $task->save();
        
        return response()->json(['Task updated successfully.', new TaskResource($task)]);
    }

    public function destroy(Task $task)
    {
        $task->delete();

        return response()->json('Task deleted successfully');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::
        orderBy('is_complete')
        ->orderByDesc('created_at')
        ->get();

        // return task index view with Task count
        return view('tasks', [
        'tasks' => $tasks,
        'tasks2' => Task::all()->count(),
        'tasks3' => Task::where('is_complete', '=', 1)->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the given request
        $this->validate($request, [
            'title' => 'required|string|max:255',
        ]);

        // create a new incomplete task with the given title
        Task::create([
            'title' => $request->input('title'),
            'is_complete' => false,
        ]);

        // flash a success message to the session
        session()->flash('status', 'Task Created!');

        // redirect to tasks index
        return redirect('/tasks');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
        $task->delete();

        session()->flash('status', 'Task deleted success!');
        return redirect('/tasks');
    }

    public function active()
    {
        $tasks = Task::where('is_complete', '=', 0)->
        orderBy('is_complete')
        ->orderByDesc('created_at')
        ->get();

        // return task index view with Task count
        return view('active', [
        'tasks' => $tasks,
        'tasks2' => Task::where('is_complete', '=', 0)->count(),
        'tasks3' => Task::where('is_complete', '=', 1)->get()
        ]);
    }

    public function completed()
    {
        $tasks = Task::where('is_complete', '=', 1)->
        orderBy('is_complete')
        ->orderByDesc('created_at')
        ->get();

        // return task index view with Task count
        return view('completed', [
        'tasks' => $tasks,
        'tasks2' => Task::where('is_complete', '=', 1)->count(),
        'tasks3' => Task::where('is_complete', '=', 1)->get()
        ]);
    }

    public function changeStatus(Request $request)
    {
        // mark the task as complete and save it
        $task = Task::find($request->id)->update(['is_complete' => $request->is_complete]);

        return response()->json(['success'=>'Status changed successfully.']);
    }

    public function deleteAll()
    {
        Task::where('is_complete', '=', 1)->delete();  

        // flash a success message to the session
        session()->flash('status', 'Delete all Completed!');

        // redirect to tasks index
        return redirect('/tasks');
    }

    public function completedAll()
    {
        Task::query()->update(['is_complete' => 1]);

        // flash a success message to the session
        session()->flash('status', 'Completed all success!');

        // redirect to tasks index
        return redirect('/tasks');
    }
}

resources/views/active.blade.php
@extends('layouts.main')

@section('container')
<section class="main">
    @if ($tasks->count() == 0)
    <h3>
        <center><i>Task active not found</i></center>
    </h3>
    @else


    <div class="dropdown">
        <input id="toggle-all" class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <div class="dropdown-content">
            <a href="/completedall">Mark all as complete</a>
        </div>
    </div>

    <ul class="todo-list">
        <!-- These are here just to show the structure of the list items -->
        <!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
        @foreach ($tasks as $task)
        <li>
            <div class="view">

                @if ($task->is_complete)

                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    <s>{{ $task->title }}</s>
                </label>
                @else
                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    {{ $task->title }}
                </label>
                @endif
                {{-- Button delete taskss --}}
                <form action="{{ route('tasks.destroy', $task->id)}}" method="POST" class="d-inline">
                    @method('delete')
                    @csrf
                    <button class="destroy" onclick="return confirm('Are you sure you want to delete ?')">
                    </button>
                </form>
            </div>
        </li>
        @endforeach
    </ul>
    @endif
</section>

<!-- This footer should be hidden by default and shown when there are todos -->
<footer class="footer">
    @if ($tasks->count() == 0)
    <ul class="filters">
        <li>
            <a class="selected" href="/">All</a>
        </li>
    </ul>
    @else
    <!-- This should be `0 items left` by default -->
    <span class="todo-count"><strong>{{$tasks2}}</strong> item left</span>
    <!-- Remove this if you don't implement routing -->
    <ul class="filters">
        <li>
            <a href="/">All</a>
        </li>
        <li>
            <a class="selected" href="/tasks/active">Active</a>
        </li>
        <li>
            <a href="/tasks/completed">Completed</a>
        </li>
    </ul>
    @if ($tasks3->count() == 0)	
        {{-- null --}}
	@else 
    <!-- Hidden if no completed items are left ↓ -->
    <form method="GET" action="{{ route('deleteall') }}">
        @csrf
        <button class="clear-completed">Clear completed</button>
    </form>
	@endif
    @endif
</footer>
@endsection

resources/views/completed.blade.php
@extends('layouts.main')

@section('container')
<section class="main">
    @if ($tasks->count() == 0)
    <h3>
        <center><i>Task completed not found</i></center>
    </h3>
    @else


    <div class="dropdown">
        <input id="toggle-all" class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <div class="dropdown-content">
            <a href="/completedall">Mark all as complete</a>
        </div>
    </div>

    <ul class="todo-list">
        <!-- These are here just to show the structure of the list items -->
        <!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
        @foreach ($tasks as $task)
        <li>
            <div class="view">

                @if ($task->is_complete)

                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    <s>{{ $task->title }}</s>
                </label>
                @else
                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    {{ $task->title }}
                </label>
                @endif
                {{-- Button delete taskss --}}
                <form action="{{ route('tasks.destroy', $task->id)}}" method="POST" class="d-inline">
                    @method('delete')
                    @csrf
                    <button class="destroy" onclick="return confirm('Are you sure you want to delete ?')">
                    </button>
                </form>
            </div>
        </li>
        @endforeach
    </ul>
    @endif
</section>

<!-- This footer should be hidden by default and shown when there are todos -->
<footer class="footer">
    @if ($tasks->count() == 0)
    <ul class="filters">
        <li>
            <a class="selected" href="/">All</a>
        </li>
    </ul>
    @else
    <!-- This should be `0 items left` by default -->
    <span class="todo-count"><strong>{{$tasks2}}</strong> item left</span>
    <!-- Remove this if you don't implement routing -->
    <ul class="filters">
        <li>
            <a href="/">All</a>
        </li>
        <li>
            <a href="/tasks/active">Active</a>
        </li>
        <li>
            <a class="selected" href="/tasks/completed">Completed</a>
        </li>
    </ul>
    @if ($tasks3->count() == 0)	
        {{-- null --}}
	@else 
    <!-- Hidden if no completed items are left ↓ -->
    <form method="GET" action="{{ route('deleteall') }}">
        @csrf
        <button class="clear-completed">Clear completed</button>
    </form>
	@endif
    @endif
</footer>
@endsection

resources/views/layouts/header.blade.php
        {{-- Header --}}
        <header class="header">
            <h1>Super2Do</h1>
            <div>
                <form method="POST" action="{{ route('tasks.store') }}">
                    @csrf
                    <input placeholder="What needs to be done?" id="title" name="title" type="text" maxlength="255"
                        class="new-todo form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                        autocomplete="off">
                    @if ($errors->has('title'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('title') }}</strong>
                    </span>
                    @endif
                </form>
            </div>
        </header>

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="stylesheet" href="{{ asset('css/base.css') }}">
    <link rel="stylesheet" href="{{ asset('css/index.css') }}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- CSS overrides - remove if you don't need it -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">

</head>

<body>
    <section class="todoapp">
        {{-- Header  --}}
        @include('layouts.header')

        {{-- Content --}}
        @yield('container')

    </section>
    
    {{-- alert success --}}
    @if (session('status'))
    <div class="alert" id="message">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{ session('status') }}
    </div>
    @endif
    <!-- Scripts here. Don't remove ↓ -->
    <script src="{{ asset('js/app.js') }}"></script>

    {{-- script  changeStatus active and complete--}}
    <script>
        function changeStatus(_this, id) {
            var is_complete = $(_this).prop('checked') == true ? 1 : 0;
            let _token = $('meta[name="csrf-token"]').attr('content');

            $.ajax({
                url: `/changestatus`,
                type: 'GET',
                data: {
                    _token: _token,
                    id: id,
                    is_complete: is_complete
                },
                success: function (result) {}
            });
        }
    </script>

    {{-- Hidden  alert success--}}
    <script>
        window.setTimeout(function () {
            $("#message").fadeTo(500, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 5000);
    </script>

</body>

</html>

resources/views/tasks.blade.php
@extends('layouts.main')

@section('container')
<section class="main">
    @if ($tasks->count() == 0)
    <h3>
        <center>Task not found</center>
    </h3>
    @else


    <div class="dropdown">
        <input id="toggle-all" class="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <div class="dropdown-content">
            <a href="/completedall">Mark all as complete</a>
        </div>
    </div>

    <ul class="todo-list">
        <!-- These are here just to show the structure of the list items -->
        <!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
        @foreach ($tasks as $task)
        <li>
            <div class="view">

                @if ($task->is_complete)

                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    <s>{{ $task->title }}</s>
                </label>
                @else
                <input class="toggle" type="checkbox" onclick="changeStatus(event.target, {{ $task->id }});"
                    {{ $task->is_complete ? 'checked' : '' }}>
                <label>
                    {{ $task->title }}
                </label>
                @endif
                {{-- Button delete taskss --}}
                <form action="{{ route('tasks.destroy', $task->id)}}" method="POST" class="d-inline">
                    @method('delete')
                    @csrf
                    <button class="destroy" onclick="return confirm('Are you sure you want to delete ?')">
                    </button>
                </form>
            </div>
        </li>
        @endforeach
    </ul>
    @endif
</section>

<!-- This footer should be hidden by default and shown when there are todos -->
<footer class="footer">
    @if ($tasks->count() == 0)

    @else
    <!-- This should be `0 items left` by default -->
    <span class="todo-count"><strong>{{$tasks2}}</strong> item left</span>
    <!-- Remove this if you don't implement routing -->
    <ul class="filters">
        <li>
            <a class="selected" href="/">All</a>
        </li>
        <li>
            <a href="/tasks/active">Active</a>
        </li>
        <li>
            <a href="/tasks/completed">Completed</a>
        </li>
    </ul>
	@if ($tasks3->count() == 0)	
		{{-- null --}}
	@else 
    <!-- Hidden if no completed items are left ↓ -->
    <form method="GET" action="{{ route('deleteall') }}">
        @csrf
        <button class="clear-completed">Clear completed</button>
    </form>
	@endif

    @endif
</footer>
@endsection